/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.matis.bonito.vista;

import java.awt.BorderLayout;
import org.matis.bonito.controller.*;
import org.matis.bonito.formularios.*;
import org.matis.bonito.model.*;

import javax.swing.*;
import java.awt.event.ActionEvent;

import static java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE;
import static java.awt.Dialog.ModalityType.TOOLKIT_MODAL;
import static java.awt.EventQueue.invokeLater;
import static java.awt.Toolkit.getDefaultToolkit;
import java.awt.event.ItemEvent;
import static java.lang.Runtime.getRuntime;
import static java.lang.System.exit;
import static java.lang.System.out;
import static javax.swing.JOptionPane.*;
import org.matis.bonito.validador.RandomGradientPanelThread;

/**
 *
 * @author oscar
 */
public class InitForm extends JFrame {

    /**
     * Creates new form InitForm
     */
    public InitForm() {
        initComponents();
        cargaComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        abrir = new javax.swing.JToggleButton();
        barraPrincipal = new javax.swing.JMenuBar();
        MenuAdmin = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuCrearIng = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuEditaIng = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuEliminaIng = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuCrearSede = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuCrearPiso = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuCreaSO = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        menuCrearEquipo = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuCrearMarca = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        menuRegisrarEquipoCert = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EntryForm");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        abrir.setText("☰");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abrir)
                .addContainerGap(791, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(abrir)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuAdmin.setMnemonic('o');
        MenuAdmin.setText("Admin");
        MenuAdmin.add(jSeparator1);

        menuCrearIng.setMnemonic('C');
        menuCrearIng.setText("Crear Ingeniero Soporte");
        MenuAdmin.add(menuCrearIng);
        MenuAdmin.add(jSeparator2);

        menuEditaIng.setMnemonic('E');
        menuEditaIng.setText("Editar Ingeniero Soporte");
        MenuAdmin.add(menuEditaIng);
        MenuAdmin.add(jSeparator4);

        menuEliminaIng.setMnemonic('m');
        menuEliminaIng.setText("Eliminar Ingeniero Soporte");
        MenuAdmin.add(menuEliminaIng);
        MenuAdmin.add(jSeparator3);

        menuCrearSede.setMnemonic('R');
        menuCrearSede.setText("Registrar sede");
        MenuAdmin.add(menuCrearSede);
        MenuAdmin.add(jSeparator5);

        menuCrearPiso.setMnemonic('e');
        menuCrearPiso.setText("Registrar piso");
        MenuAdmin.add(menuCrearPiso);
        MenuAdmin.add(jSeparator7);

        menuCreaSO.setMnemonic('o');
        menuCreaSO.setText("Registrar sistema operativo");
        MenuAdmin.add(menuCreaSO);
        MenuAdmin.add(jSeparator10);

        menuCrearEquipo.setMnemonic('t');
        menuCrearEquipo.setText("Registrar tipo equipo");
        MenuAdmin.add(menuCrearEquipo);
        MenuAdmin.add(jSeparator6);

        menuCrearMarca.setMnemonic('g');
        menuCrearMarca.setText("Registrar marca");
        MenuAdmin.add(menuCrearMarca);
        MenuAdmin.add(jSeparator9);

        menuSalir.setMnemonic('S');
        menuSalir.setText("Salir");
        MenuAdmin.add(menuSalir);
        MenuAdmin.add(jSeparator8);

        barraPrincipal.add(MenuAdmin);

        jMenu1.setText("Crear");

        menuRegisrarEquipoCert.setText("Registrar Equipo");
        jMenu1.add(menuRegisrarEquipoCert);

        barraPrincipal.add(jMenu1);

        setJMenuBar(barraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1022, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cargaComponentes() {
        var soporte = new IngenieroSoporte("Oscar Antonio", "Lopez", "Gonzalez", "65070610");
        var sede = new Sedes("Torre Tp", "F-000000000001");
        var piso = new Piso("PB1", "P-000000000001");
        var so = new SistemaOperativo("Windows 7 Pro", "x32", "S-000000000001");
        var tipoEquipo = new TipoEquipo("PC", "E-000000000001");
        var marcas = new MarcaEquipo("DELL", "M-000000000001", "000000000001");
        var ingSopController = new IngSopController();
        var sedesCotroller = new SedeController();
        var pisoController = new PisoController();
        var sistemaOpeControler = new SistemaOperativoController();
        var tipoEquipoController = new TipoEquipoController();
        var marcaControlador = new MarcaEquipoController();
        this.add(new RandomGradientPanelThread(), BorderLayout.CENTER);
        /*
        if (ingSopController.crearIngSop(soporte)) {
            out.println("Valor guardado");
        } else {
            out.println("No se logro el registro");
        }
        if (sedesCotroller.crearSede(sede)) {
            out.println("Sede guardada");
        } else {
            out.println("No se logro el registro de la sede......");
        }
        if (pisoController.crearPiso(piso)) {
            out.println("Piso guardado");
        } else {
            out.println("No se logro el registro del piso......");
        }
        if (sistemaOpeControler.crearSisOpe(so)) {
            out.println("Sistema Operativo creado");
        } else {
            out.println("No se logro el registro del sistema operativo......");
        }
        if (marcaControlador.crearMarcaEquipo(marcas)) {
            out.println("La marca de equipo se a creado........");
        } else {
            out.println("No se logro el registro de la marca......");
        }


        if (tipoEquipoController.crearTipoEquipo(tipoEquipo)) {
            out.println("Tipo creado");
        } else {
            out.println("No se logro el registro del tipo......");
        }
        if (ingSopController.eliminarIngsop("23445564")) {
            out.println("Eliminado");
        } else {
            out.println("Sin eliminar");
        }
        var updatesoporte = new IngenieroSoporte("Matias", "Peque Bonito", "Mi Niño bonito", "20201982");
        if (ingSopController.actualizaIngSop("65070600", updatesoporte)) {
            out.println("Actualizados");
        } else {
            out.println("No Actualizados");
        }*/
        ingSopController.obtenerIngSop().forEachOrdered(out::println);
        ingSopController.otenerIngSopNumEmp("23425564").forEachOrdered(out::println);

        menuCrearIng.addActionListener(e -> invokeLater(() -> new CrearIngSop(new JFrame(), true).setVisible(true)));
        menuEditaIng.addActionListener(e -> invokeLater(() -> new EditarIngSop(new JFrame(), true).setVisible(true)));
        menuEliminaIng.addActionListener(e -> invokeLater(() -> new ElimnarIngSop(new JFrame(), true).setVisible(true)));
        menuCrearSede.addActionListener(e -> invokeLater(() -> new CrearSede(new JFrame(), true).setVisible(true)));
        menuCrearPiso.addActionListener(e -> invokeLater(() -> new CrearPiso(new JFrame(), true).setVisible(true)));
        menuCreaSO.addActionListener(e -> invokeLater(() -> new CrearSO(new JFrame(), true).setVisible(true)));
        menuCrearEquipo.addActionListener(e -> invokeLater(() -> new CreaTipoEquipo(new JFrame(), true).setVisible(true)));
        menuCrearMarca.addActionListener(e -> invokeLater(() -> new CrearMarca(new JFrame(), true).setVisible(true)));
        menuSalir.addActionListener(e -> {
            cerrarPrincipal(e);
        });
        menuRegisrarEquipoCert.addActionListener(e -> invokeLater(() -> new RegistraCertificacion(new JFrame(), true).setVisible(true)));

        abrir.addItemListener(e -> {
            int estado = e.getStateChange();
            if (estado == ItemEvent.SELECTED) {
                panelPrincipal.setVisible(false);
            } else {
                panelPrincipal.setVisible(true);
            }

        });

    }

    private void cerrarPrincipal(ActionEvent e) {
        final var pane = new JOptionPane("Desea cerrar la aplicación", QUESTION_MESSAGE, OK_CANCEL_OPTION);
        final var dialogo = pane.createDialog(this, "Monitor");
        dialogo.setModal(true);
        dialogo.setModalExclusionType(APPLICATION_EXCLUDE);
        dialogo.setModalityType(TOOLKIT_MODAL);
        dialogo.setVisible(true);
        dialogo.dispose();
        dialogo.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        var value = ((Integer) pane.getValue());
        getDefaultToolkit().beep();
        //var close = JOptionPane.showConfirmDialog(this, "Desea cerrar la aplicación", "Monitor", JOptionPane.YES_NO_OPTION);
        if (value == YES_OPTION) {
            revalidate();
            repaint();
            dispose();
            System.gc();
            getRuntime().gc();
            exit(0);
        } else {
            final var paneop = new JOptionPane("Cancelando cerrar aplicación", INFORMATION_MESSAGE);
            final var dialogoOp = paneop.createDialog(this, "Monitor");
            dialogoOp.setModal(true);
            dialogoOp.setModalExclusionType(APPLICATION_EXCLUDE);
            dialogoOp.setModalityType(TOOLKIT_MODAL);
            dialogoOp.setVisible(true);
            dialogoOp.dispose();
            dialogoOp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            getDefaultToolkit().beep();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JToggleButton abrir;
    private javax.swing.JMenuBar barraPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem menuCreaSO;
    private javax.swing.JMenuItem menuCrearEquipo;
    private javax.swing.JMenuItem menuCrearIng;
    private javax.swing.JMenuItem menuCrearMarca;
    private javax.swing.JMenuItem menuCrearPiso;
    private javax.swing.JMenuItem menuCrearSede;
    private javax.swing.JMenuItem menuEditaIng;
    private javax.swing.JMenuItem menuEliminaIng;
    private javax.swing.JMenuItem menuRegisrarEquipoCert;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
