/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.matis.bonito.formularios;

import org.matis.bonito.controller.SedeController;

import static java.awt.Toolkit.getDefaultToolkit;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;

import java.awt.*;

import static java.lang.System.out;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import org.matis.bonito.model.Sedes;

/**
 *
 * @author oscar
 */
public class CrearSede extends JDialog {

    /**
     * Creates new form CrearSede
     *
     * @param parent
     * @param modal
     */
    public CrearSede(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        misComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoSede = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        guardar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CrearSede");
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        jLabel1.setText("Nombre sede:");

        textoSede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoSedeKeyReleased(evt);
            }
        });

        guardar.setMnemonic('G');
        guardar.setText("Guardar");

        cerrar.setMnemonic('C');
        cerrar.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoSede, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(cerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(330, 160));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void misComponentes() {
        guardar.setEnabled(false);
        textoSede.requestFocus();
        textoSede.addActionListener(e -> {
            var textSede = textoSede.getText();
            if (textSede.isEmpty()) {
                showMessageDialog(this, "El campo sede está vacío", "Monitor", ERROR_MESSAGE);
                getDefaultToolkit().beep();
                textoSede.requestFocus();
            } else {
                var sedeControler = new SedeController();
                var sedescontrol = sedeControler.obtenerSedeActivo(textSede);
                if(sedescontrol != null) {
                    showMessageDialog(this, "Ya existe el registro de la sede", "Monitor", ERROR_MESSAGE);
                    getDefaultToolkit().beep();
                    guardar.setEnabled(false);
                    textoSede.selectAll();
                    textoSede.setSelectionColor(Color.CYAN);
                    textoSede.requestFocus();
                } else {
                    if(textSede.length() == 1) {
                        showMessageDialog(this, "El nombre de la sede debe de contener más caracteres", "Monitor", ERROR_MESSAGE);
                        guardar.setEnabled(false);
                        getDefaultToolkit().beep();
                        textoSede.selectAll();
                        textoSede.setSelectionColor(Color.CYAN);
                        textoSede.requestFocus();
                    } else {
                        guardar.setEnabled(true);
                        ((JComponent) e.getSource()).transferFocus();
                    }
                }
            }
        });
        this.getRootPane().setDefaultButton(cerrar);
        guardar.addActionListener(e -> guardandoSede());
        cerrar.addActionListener(e -> this.dispose());
    }

    private void textoSedeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoSedeKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_textoSedeKeyReleased

    private void guardandoSede() {
        var textSede = textoSede.getText();
        if (textSede.isEmpty()) {
            textoSede.requestFocus();
            getDefaultToolkit().beep();
        } else {
            var sedeControler = new SedeController();
            showMessageDialog(this, textSede, "Monitor", ERROR_MESSAGE);
            var sedeid = sedeControler.obtenerSedeActivo(textSede);
            showMessageDialog(this, sedeid, "Monitor", ERROR_MESSAGE);
            if (sedeid != null) {
                showMessageDialog(this, "No hay registro", "Monitor", JOptionPane.INFORMATION_MESSAGE);
                /*var incrementar = Integer.parseInt(sedeid.getCodigo_sede()) + 1;
                var miSede = new Sedes(textSede, String.format("A%06d", incrementar));
                if (sedeControler.crearSede(miSede)) {
                    System.out.println(miSede);
                    guardar.setEnabled(false);
                    showMessageDialog(this, "Se registro la sede", "Monitor", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    textoSede.requestFocus();
                    textoSede.selectAll();
                    textoSede.setSelectionColor(Color.red);
                    getDefaultToolkit().beep();
                    showMessageDialog(this, "No se registro la sede", "Monitor", ERROR_MESSAGE);
                }*/
            } else {
                showMessageDialog(this, sedeid, "Monitor", JOptionPane.INFORMATION_MESSAGE);
                
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField textoSede;
    // End of variables declaration//GEN-END:variables

    private int nuevoNumeroFolio = 1;

}
