/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.matis.bonito.formularios;

import javax.swing.JFrame;

/**
 *
 * @author oscar
 */
public class ImagenDialog extends javax.swing.JDialog {

    /**
     * Creates new form ImagenDialog
     * @param parent
     * @param modal
     */
    public ImagenDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        archivosImagenes = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);

        archivosImagenes.setBackground(new java.awt.Color(255, 255, 255));
        archivosImagenes.setDialogTitle("Cargar imagen");
        archivosImagenes.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        getContentPane().add(archivosImagenes, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(528, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFileChooser archivosImagenes;
    // End of variables declaration//GEN-END:variables
}
